[project]
name = "apfel"
version = "0.3.0"
description = "A Python functional extras library providing a set of quality-of-life utilities."
authors = [
    {name = "Yixuan-Wang", email = "tom-yx_wang@outlook.com"},
]
dependencies = [
    "typing-extensions>=4.12.0",
]
requires-python = ">=3.11"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[build-system]
requires = ["uv_build>=0.9.0"]
build-backend = "uv_build"

[dependency-groups]
doc = [
    "mkdocs>=1.6.0",
    "mkdocstrings[python]>=0.25.1",
    "mkdocs-material>=9.5.24",
    "mkdocs-awesome-nav>=3.0.0",
    "mike>=2.1.0",
]
test = [
    "pytest>=8.3.4",
    "pytest-cov>=7.0.0",
]
dev = [
    "tox-uv",
    "ipython>=9",
    "ipdb",
]

[tool.uv.build-backend]

[tool.ruff]
[tool.ruff.lint]
extend-select = ["ISC", "COM818"]
ignore = ["E741", "F821"]
flake8-implicit-str-concat.allow-multiline = false

[tool.ty.environment]
python-version = "3.12"

[tool.tox]
requires = ["tox>=4"]
env_list = ["3.14", "3.13", "3.12", "3.11"]

[tool.tox.env_run_base]
dependency_groups = ["test"]
description = "Run test under {base_python}"
commands = [["pytest", "test/"]]
runner = "uv-venv-lock-runner"
