[project]
name = "apfel"
version = "0.2.1"
description = "A personal functional extension library."
authors = [
    {name = "Yixuan-Wang", email = "tom-yx_wang@outlook.com"},
]
dependencies = [
    "typing-extensions>=4.12.0",
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}
classifiers = ["Private :: Do Not Upload"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
doc = [
    "mkdocs>=1.6.0",
    "mkdocstrings[python]>=0.25.1",
    "mkdocs-material>=9.5.24",
    "mkdocs-awesome-nav>=3.0.0",
    "mike>=2.1.0",
]
test = [
    "pytest>=8.3.4",
    "pytest-cov>=7.0.0",
]
dev = [
    "tox-uv",
    "ipython>=9",
    "ipdb",
    "marimo",
]

[tool.hatch.build.targets.sdist]
only-include = ["uv.lock", "src", "test"]

[tool.ruff]
[tool.ruff.lint]
extend-select = ["ISC", "COM818"]
ignore = ["E741", "F821"]
flake8-implicit-str-concat.allow-multiline = false

[tool.tox]
requires = ["tox>=4"]
env_list = ["3.14", "3.13", "3.12", "3.11"]

[tool.tox.env_run_base]
dependency_groups = ["test"]
description = "Run test under {base_python}"
commands = [["pytest", "test/"]]
runner = "uv-venv-lock-runner"