from collections.abc import Callable

class Once[T]:
    def __init__(self): ...
    def set(self, value: T) -> None: ...
    def get(self) -> T: ...
    def get_or_init(self, init_fn: Callable[[], T]) -> T: ...
    def is_set(self) -> bool: ...


def lazy_init[T](func: Callable[[], T]) -> Callable[[], T]: ...
