from collections.abc import Callable
import apfel.container.maybe as _maybe
import apfel.container.result as _result

class Once[T]:
    def __init__(self): ...
    def __class_getitem__[U](cls, item: U) -> Once[U]: ...
    @classmethod
    def of_hint[U](cls, type: type[U], /) -> Once[U]: ...

    def __bool__(self) -> bool: ...
    def get(self) -> _maybe.Maybe[T]: ...
    def get_or_init(self, f: Callable[[], T], /) -> T: ...
    def set(self, value: T) -> _result.Result[None, T]: ...
    def unwrap(self) -> T: ...

class OnceLock[T]:
    def __init__(self) -> None: ...
    def __class_getitem__[U](cls, item: U) -> OnceLock[U]: ...
    def __bool__(self) -> bool: ...
    def get(self) -> _maybe.Maybe[T]: ...
    def get_or_init(self, f: Callable[[], T], /) -> T: ...
    def set(self, value: T) -> _result.Result[None, T]: ...
    def unwrap(self) -> T: ...

class Lazy[T]:
    def __init__(self, f: Callable[[], T]) -> None: ...
    def __class_getitem__[U](cls, item: U) -> Lazy[U]: ...
    def __bool__(self) -> bool: ...
    def __call__(self) -> T: ...
    def unwrap(self) -> T: ...
    def value(self) -> T: ...

class LazyLock[T]:
    def __init__(self, f: Callable[[], T]) -> None: ...
    def __class_getitem__[U](cls, item: U) -> LazyLock[U]: ...
    def __bool__(self) -> bool: ...
    def __call__(self) -> T: ...
    def unwrap(self) -> T: ...
    def value(self) -> T: ...