from collections.abc import Callable

class Once[T]:
    def __init__(self): ...
    def __class_getitem__[U](cls, item: U) -> Once[U]: ...
    def __bool__(self) -> bool: ...
    def get_or_init(self, f: Callable[[], T], /) -> T: ...
    def set(self, value: T) -> None: ...
    def unwrap(self) -> T: ...

class Lazy[T]:
    def __init__(self, f: Callable[[], T]) -> None: ...
    def __class_getitem__[U](cls, item: U) -> Lazy[U]: ...
    def __bool__(self) -> bool: ...
    def __call__(self) -> T: ...
    def unwrap(self) -> T: ...
    def value(self) -> T: ...

