from ast import Call
from collections.abc import Callable
from typing import Any, overload
from typing_extensions import Self

from apfel.core.monad import Monad 

class Value[T](Monad[T]):
    __slots__ = ("_value", )

    def __init__(self, value: T): ...

    def __class_getitem__[U](cls, item: type[U]) -> Value[U]: ...

    def apply[R](self, f: Value[Callable[[T], R]]) -> Value[R]: ...
    def bind[R](self, func: Callable[[T], Value[R]]) -> Value[R]: ...
    def done(self) -> T: ...
    def map[U](self, func: Callable[[T], U]) -> Value[U]: ...
    @overload
    def pipe(self, func: Callable[[T], T]) -> Self: ...
    @overload
    def pipe(self, func: Callable[[T], None]) -> Self: ...
    @overload
    @classmethod
    def pure[R](cls, value: R) -> Value[R]: ...
    @overload
    @classmethod
    def pure(cls, value: T) -> Value[T]: ...
    def run[R](self, func: Callable[[T], R]) -> R: ...
    def tap(self, func: Callable[[T], Any]) -> Value[T]: ...

