from collections.abc import Callable
from typing import Any

from apfel.core.monad import Functor

class Value[T](Functor):
    __slots__ = ("_value", )

    def __init__(self, value: T): ...

    def __class_getitem__[U](cls, item: type[U]) -> Value[U]: ...

    def done(self) -> T: ...
    def map[U](self, f: Callable[[T], U]) -> Value[U]: ...
    def mutate(self, f: Callable[[T], Any]) -> Value[T]: ...
    def pipe[U](self, f: Callable[[T], U]) -> Value[U]: ...
    def tap(self, f: Callable[[T], Any]) -> Value[T]: ...

