from collections.abc import Callable
from typing import Any, overload, override
from typing_extensions import Self

from apfel.core.monad import Monad

class Value[T](Monad[T]):
    __slots__ = ("_value",)

    def __init__(self, value: T): ...
    def __class_getitem__[U](cls, item: type[U]) -> Value[U]: ...
    @override
    def apply[R](self, func: Value[Callable[[T], R]], /) -> Value[R]: ...
    @override
    def bind[R](self, func: Callable[[T], Value[R]], /) -> Value[R]: ...
    def done(self) -> T: ...
    def map[U](self, func: Callable[[T], U], /) -> Value[U]: ...
    def update(self, func: Callable[[T], T], /) -> Self: ...
    def mutate(self, func: Callable[[T], Any], /) -> Self: ...
    @overload
    @classmethod
    def pure[R](cls, value: R, /) -> Value[R]: ...
    @overload
    @classmethod
    def pure(cls, value: T, /) -> Value[T]: ...
    def run[R](self, func: Callable[[T], R], /) -> R: ...
    def tap(self, func: Callable[[T], Any], /) -> Value[T]: ...
