from abc import abstractmethod
import ast
from collections.abc import Callable
from typing import Any, overload, TypeVar

U = TypeVar("U", covariant=False, contravariant=False)

@overload
def affirm(value: Any, predicate: type[is_type[U]]) -> U: ...
@overload
def affirm[T](value: Any, predicate: type[type[T]]) -> T: ...
@overload
def affirm[T](value: T, predicate: AffirmPredicate[T]) -> T: ...
@overload
def affirm[T](value: T, predicate: Callable[[T], bool]) -> T: ...
@overload
def affirm[T](value: T, predicate: Callable[[T], Any]) -> T: ...
@overload
def affirm[T](value: T) -> T: ...
@overload
def affirm[T](value: T, predicate: bool) -> T: ...
@overload
def affirm[T](value: T, predicate: Any = None) -> T: ...

class AffirmPredicate[T]:
    @abstractmethod
    def test(self, value: T) -> bool: ...
    def __call__(self, value: T) -> bool: ...
    def fail_message(self, *, argument_expr: ast.expr | None, value: T) -> str: ...

class is_type(AffirmPredicate[U]): ...
