from abc import abstractmethod
from collections.abc import Callable, Iterable, Iterator as VanillaIterator
from typing import Any, Self, Concatenate, TypeVar, overload

from apfel.container.maybe import Maybe
from apfel.container.result import Result
import apfel.core.dispatch as _dispatch


I = TypeVar("I", covariant=True)
class Iterator(_dispatch.ABCDispatch, VanillaIterator[I]):
    @abstractmethod
    def __next__(self) -> I: ...
    def __iter__(self) -> Iterator[I]: ...
    #
    @overload
    def next(self) -> Maybe[I]: ...
    @overload
    def next[Item](self: VanillaIterator[Item]) -> Maybe[Item]: ...
    #
    @overload
    def advance_by(self, n: int, /) -> Result[None, int]: ...
    @overload
    def advance_by[Item](self: VanillaIterator[Item], n: int, /) -> Result[None, int]: ...
    #
    @overload
    def all(self, pred: Callable[[I], bool], /) -> bool: ...
    @overload
    def all[Item](self: VanillaIterator[Item], pred: Callable[[Item], bool], /) -> bool: ...
    #
    @overload
    def any(self, pred: Callable[[I], bool], /) -> bool: ...
    @overload
    def any[Item](self: VanillaIterator[Item], pred: Callable[[Item], bool], /) -> bool: ...
    #
    @overload
    def chain(self, *others: Iterator[I]) -> Iterator[I]: ...
    @overload
    def chain[Item](self: VanillaIterator[Item], *others: VanillaIterator[Item]) -> Iterator[Item]: ...
    #
    @overload
    def count(self) -> int: ...
    @overload
    def count[Item](self: VanillaIterator[Item]) -> int: ...
    #
    @overload
    def enumerate(self, init: int = 0) -> Iterator[tuple[int, I]]: ...
    @overload
    def enumerate[Item](self: VanillaIterator[Item], init: int = 0) -> Iterator[tuple[int, Item]]: ...
    #
    @overload
    def eq(self, other: Iterator[I], /) -> bool: ...
    @overload
    def eq(self, other: VanillaIterator[I], /) -> bool: ...
    @overload
    def eq[Item](self: VanillaIterator[Item], other: VanillaIterator[Item], /) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    #
    @overload
    def filter(self, pred: Callable[[I], bool], /) -> Iterator[I]: ...
    @overload
    def filter[Item](self: VanillaIterator[Item], pred: Callable[[Item], bool], /) -> Iterator[Item]: ...
    #
    @overload
    def filter_map[U](self, pred: Callable[[I], Maybe[U]], /) -> Iterator[U]: ...
    @overload
    def filter_map[Item, U](self: VanillaIterator[Item], pred: Callable[[Item], Maybe[U]], /) -> Iterator[U]: ...
    #
    @overload
    def find(self, pred: Callable[[I], bool], /) -> Maybe[I]: ...
    @overload
    def find[Item](self: VanillaIterator[Item], pred: Callable[[Item], bool], /) -> Maybe[Item]: ...
    #
    @overload
    def find_map[U](self, pred: Callable[[I], Maybe[U]], /) -> Maybe[U]: ...
    @overload
    def find_map[Item, U](self: VanillaIterator[Item], pred: Callable[[Item], Maybe[U]], /) -> Maybe[U]: ...
    #
    @overload
    def flat_map[U](self, func: Callable[[I], Iterable[U]], /) -> Iterator[U]: ...
    @overload
    def flat_map[Item, U](self: VanillaIterator[Item], func: Callable[[Item], Iterable[U]], /) -> Iterator[U]: ...
    #
    @overload
    def flatten[Item](self: Iterator[Iterator[Item]]) -> Iterator[Item]: ...
    @overload
    def flatten[Item](self: Iterator[VanillaIterator[Item]]) -> Iterator[Item]: ...
    @overload
    def flatten[Item](self: Iterator[Iterable[Item]]) -> Iterator[Item]: ...
    #
    @overload
    def fold[T](self, init: T, func: Callable[[T, I], T]) -> T: ...
    @overload
    def fold[Item, T](self: VanillaIterator[Item], init: T, func: Callable[[T, Item], T]) -> T: ...
    #
    @overload
    def for_each(self, func: Callable[[I], Any]) -> None: ...
    @overload
    def for_each[Item](self: VanillaIterator[Item], func: Callable[[Item], Any]) -> None: ...
    #
    @overload
    def last(self) -> Maybe[I]: ...
    @overload
    def last[Item](self: VanillaIterator[Item]) -> Maybe[Item]: ...
    #
    @overload
    def map[U](self, func: Callable[[I], U]) -> Iterator[U]: ...
    @overload
    def map[Item, U](self: VanillaIterator[Item], func: Callable[[Item], U]) -> Iterator[U]: ...
    #
    @overload
    def nth(self, n: int, /) -> Maybe[I]: ...
    @overload
    def nth[Item](self: VanillaIterator[Item], n: int, /) -> Maybe[Item]: ...
    #
    @overload
    def pipe[**P, T](
        self,
        func: Callable[Concatenate[Iterable[I], P], T],
        /,
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> T: ...
    @overload
    def pipe[Item, **P, T](
        self: VanillaIterator[Item],
        func: Callable[Concatenate[Iterable[Item], P], T],
        /,
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> T: ...
    #
    @overload
    def position(self, pred: Callable[[I], bool], /) -> Maybe[int]: ...
    @overload
    def position[Item](self: VanillaIterator[Item], pred: Callable[[Item], bool], /) -> Maybe[int]: ...
    #
    @overload
    def reduce(self, func: Callable[[I, I], I]) -> Maybe[I]: ...
    @overload
    def reduce[Item](self: VanillaIterator[Item], func: Callable[[Item, Item], Item]) -> Maybe[Item]: ...
    #
    @overload
    def skip(self, n: int, /) -> Iterator[I]: ...
    @overload
    def skip[Item](self: VanillaIterator[Item], n: int, /) -> Iterator[Item]: ...
    #
    @overload
    def skip_while(self, pred: Callable[[I], bool], /) -> Iterator[I]: ...
    @overload
    def skip_while[Item](self: VanillaIterator[Item], pred: Callable[[Item], bool], /) -> Iterator[Item]: ...
    #
    @overload
    def step_by(self, step: int, /) -> Iterator[I]: ...
    @overload
    def step_by[Item](self: VanillaIterator[Item], step: int, /) -> Iterator[Item]: ...
    #
    @overload
    def take(self, n: int, /) -> Iterator[I]: ...
    @overload
    def take[Item](self: VanillaIterator[Item], n: int, /) -> Iterator[Item]: ...
    #
    @overload
    def take_while(self, pred: Callable[[I], bool], /) -> Iterator[I]: ...
    @overload
    def take_while[Item](self: VanillaIterator[Item], pred: Callable[[Item], bool], /) -> Iterator[Item]: ...

class IteratorAdaptor[I](Iterator[I], VanillaIterator[I]):
    def __init__(self, iterator: VanillaIterator[I]): ...
    def __next__(self) -> I: ...
    def __iter__(self) -> Self: ...

@overload
def itrt[I](iterable: Iterator[I], /) -> Iterator[I]: ...
@overload
def itrt[I](iterable: Iterable[I], /) -> Iterator[I]: ...
@overload
def itrt[I](iterable: VanillaIterator[I], /) -> Iterator[I]: ...

__all__ = ["Iterator", "itrt"]
