from typing import NoReturn, overload

def identity[T](x: T) -> T: ...

@overload
def imperative() -> None: ...
@overload
def imperative[*Ts, R](*exprs: *tuple[*Ts, R]) -> R: ...

def todo(message: str | None = None) -> NoReturn: ...

def unimplemented(message: str | None = None) -> NoReturn: ...
