from __future__ import annotations
from collections.abc import Callable
from typing import Any, Concatenate, Mapping, Never, Sequence, overload

class FunctionObject:
    @overload
    def __new__[R](cls, func: Callable[[], R]) -> FunctionObjectA0[R]: ...
    @overload
    def __new__[T, R](cls, func: Callable[[T], R]) -> FunctionObjectA1[T, R]: ...
    @overload
    def __new__[T, **P, R](
        cls, func: Callable[Concatenate[T, P], R]
    ) -> FunctionObjectA1P[T, P, R]: ...
    @overload
    def __new__[**P, R](cls, func: Callable[P, R]) -> FunctionObjectA0P[P, R]: ...

class FunctionObjectA0[R](FunctionObject):
    def __call__(self) -> R: ...
    @overload
    def __mod__(self, value: tuple[()]) -> R: ...
    @overload
    def __mod__(self, value: Sequence) -> R: ...
    @overload
    def __mod__(self, value: Mapping) -> R: ...

class FunctionObjectA1[T, R](FunctionObject):
    def __call__(self, value: T) -> R: ...
    def __or__(self, value: T) -> R: ...
    def __rand__(self, lhs: T) -> R: ...
    def __matmul__(self, value: T) -> R: ...
    def __pow__(self, value: T) -> R: ...
    @overload
    def __mod__(self, value: tuple[T]) -> R: ...
    @overload
    def __mod__(self, value: Sequence) -> R: ...
    @overload
    def __mod__(self, value: Mapping) -> R: ...

class FunctionObjectA1P[T, **P, R](FunctionObject):
    def __call__(self, value: T, *args: P.args, **kwargs: P.kwargs) -> R: ...
    @overload
    def __mod__(self, value: tuple[T, ...]) -> R: ...
    @overload
    def __mod__(self, value: Sequence) -> R: ...
    @overload
    def __mod__(self, value: Mapping) -> R: ...

class FunctionObjectA0P[**P, R](FunctionObject):
    def __call__(self, *args: P.args, **kwargs: P.kwargs) -> R: ...
    @overload
    def __mod__(self, value: Sequence) -> R: ...
    @overload
    def __mod__(self, value: Mapping) -> R: ...

@overload
def fob[F: Callable](func: F, /) -> F: ...
@overload
def fob[*Fs](*funcs: *Fs) -> tuple[*Fs]: ...
@overload
def reveal_fob[R](func: Callable[[], R], /) -> FunctionObjectA0[R]: ...
@overload
def reveal_fob[T, R](func: Callable[[T], R], /) -> FunctionObjectA1[T, R]: ...
@overload
def reveal_fob[T, **P, R](
    func: Callable[Concatenate[T, P], R],
    /,
) -> FunctionObjectA1P[T, P, R]: ...
@overload
def reveal_fob[**P, R](func: Callable[P, R], /) -> FunctionObjectA0P[P, R]: ...
@overload
def reveal_fob(func: Callable, /) -> FunctionObject: ...
