name: Build 

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
  
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          pdm install --prod
  
      - name: Build
        run: |
          pdm build

      - name: Upload Distributions
        uses: actions/upload-artifact@v4
        with:
          path: dist/*
