name: Test

on:
  push:
    branches:
      - main
      - ci*
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']

    steps:
      - uses: actions/checkout@v4
  
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Test Dependencies
        run: |
          pdm sync -d -G test
  
      - name: Run Tests
        run: |
          pdm run -v pytest test --junitxml=junit/test-results-${{ matrix.python-version }}.xml

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: junit/test-results-${{ matrix.python-version }}.xml
        if: ${{ always() }}
